**1. Створення масивів**

Створіть (кожен пункт оцінюється в 0.5 бала):
- Масив зі списку `[5, 15, 25, 35, 45]`
- Масив з нулів розміром 7
- Масив з одиниць розміром 6
- Масив з числами від 10 до 19 використовуючи `np.arange()`

In [57]:
import numpy as np
from numpy.ma.core import sqrt, min_val

arr = np.array([5, 15, 25, 35, 45])
print(arr)
zero_array = np.zeros(7)
print(zero_array)
ones_array = np.ones(6)
print(ones_array)
range_array = np.arange(10, 20)
print(arange_array)


[ 5 15 25 35 45]
[0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[10 11 12 13 14 15 16 17 18 19]



---

**2. Базові операції**

Створіть Numpy-масив зі значеннями [12, 24, 36, 48, 60].

Виконайте наступні операції над **оригінальним** масивом і запишіть у нову змінну результат (кожен пункт оцінюється в 0.5 бала):
- Помножте всі елементи на 2
- Додайте до всіх елементів 10
- Піднесіть всі елементи до квадрату
- Обчисліть квадратний корінь з усіх елементів

Виведіть результат виконання кожної операції.

In [58]:
arr = np.array([12, 24, 36, 48, 60])
print("Original array: ", arr)
multi_arr = arr * 2
print("Multiplied by 2: ", multi_arr)
plus_arr = arr + 10
print("Plus 10: ", plus_arr)
squared_arr = arr ** 2
print("Squared array: ", squared_arr)
square_root_arr = sqrt(arr)
print("Square root array: ", square_root_arr)

Original array:  [12 24 36 48 60]
Multiplied by 2:  [ 24  48  72  96 120]
Plus 10:  [22 34 46 58 70]
Squared array:  [ 144  576 1296 2304 3600]
Square root array:  [3.4641016151377544 4.898979485566356 6.0 6.928203230275509
 7.745966692414834]



---

**3. Статистичні функції**

Створіть Numpy-масив `data` зі значеннями [18, 27, 33, 41, 52, 68, 79].

Обчисліть використовуючи функціонал numpy (кожен пункт оцінюється в 0.5 бала):
- Середнє значення
- Мінімум
- Максимум
- Суму всіх елементів

In [59]:
data = np.array([18, 27, 33, 41, 52, 68, 79])
mean_val = np.mean(data)
print(f"Mean value: {mean_val}")
min_val = np.min(data)
print(f"Min value: {min_val}")
max_val = np.max(data)
print(f"Max value: {max_val}")
sum_val = np.sum(data)
print(f"Sum value: {sum_val}")

Mean value: 45.42857142857143
Min value: 18
Max value: 79
Sum value: 318



---

**4. Індексація**

Створіть Numpy-масив `arr` зі значеннями [15, 22, 35, 44, 58, 67].

Виведіть (кожен пункт оцінюється в 0.5 бала):
- Перший елемент
- Останній елемент
- Елементи з індексами 1 до 3
- Елементи більші за 40

In [60]:
arr = np.array([15, 22, 35, 44, 58, 67])
print(f"First element: {arr[0]}")
print(f"Last element: {arr[-1]}")
print(f"Elements range with indexes 1-3: {arr[1:4]}")
print(f"Elements greater than 40: {arr[arr > 40]}")

First element: 15
Last element: 67
Elements range with indexes 1-3: [22 35 44]
Elements greater than 40: [44 58 67]



---


**5. Двовимірні масиви**

Задано матрицю 3x3.

Виконайте наступні дії з функціоналом Numpy (кожен пункт оцінюється в 0.5 бала):
- Виведіть форму (shape) матриці
- Виведіть перший рядок
- Виведіть другу колонку
- Обчисліть суму всіх елементів
- Обчисліть середнє всіх елементів

In [61]:
matrix = np.array([[2, 4, 6],
                   [8, 10, 12],
                   [14, 16, 18]])

In [62]:
print(f"The shape of matrix: {matrix.shape}")
print(f"The first row of the matrix: {matrix[0]}")
print(f"The second column of the matrix: {matrix[:,1]}")
print(f"The elements sum: {matrix.sum()}")
print(f"The elements mean: {matrix.mean()}")

The shape of matrix: (3, 3)
The first row of the matrix: [2 4 6]
The second column of the matrix: [ 4 10 16]
The elements sum: 90
The elements mean: 10.0
